const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('dist/client/index.html','utf8');
assert.match(html,/id="bgm-modal"[^>]+onclick="if\(event\.target===this\)closeBgm\(\)"/);
assert.match(html,/id="bgm-modal-close"[^>]+onclick="closeBgm\(\)"/);
assert.match(html,/#bgm-modal \.modal-box \{[^}]*max-height:[^}]*overflow-y:auto/);
const source=html.slice(html.indexOf('const bgm = {'),html.indexOf('const DIRECT_POINT_GAMES'));
let blob,plays=0,splashDismissed=false,splashRemoved=false;const listeners={};const nodes=new Proxy({}, {get:(o,k)=>o[k]??=( {value:0,checked:false,style:{},classList:{add(v){if(k==='splash-screen'&&v==='dismissed')splashDismissed=true;},remove(){}},addEventListener(event,fn){if(event==='transitionend')fn();},remove(){if(k==='splash-screen')splashRemoved=true;},focus(){},querySelector(){return {};}})});
const ctx={localStorage:{getItem:()=>null,setItem(){}},document:{hidden:false,body:{classList:{remove(){}}},addEventListener:(k,v)=>listeners[k]=v,getElementById:k=>nodes[k]},URL:{createObjectURL:b=>(blob=b,'blob:test'),revokeObjectURL(){}},Blob,DataView,ArrayBuffer,Math,Number,JSON,window:{},setTimeout:f=>f(),escapeHtml:s=>s,showToast(){},saveData:{profile:{onboardingComplete:true}},gameDelay:f=>f(),openProfile(){},Audio:class{constructor(src){this.src=src;this.paused=true;this.events={};}addEventListener(k,v){this.events[k]=v;}play(){this.paused=false;plays++;this.events.play?.();this.events.playing?.();return Promise.resolve();}pause(){this.paused=true;this.events.pause?.();}}};
vm.createContext(ctx);vm.runInContext(source,ctx);
(async()=>{for(let track=0;track<2;track++){vm.runInContext(`makeBgm(${track})`,ctx);const b=Buffer.from(await blob.arrayBuffer());assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.readUInt32LE(40),b.length-44);let max=0;for(let i=44;i<b.length;i+=2)max=Math.max(max,Math.abs(b.readInt16LE(i)));assert(max>1000&&max<32767);}
assert.equal(vm.runInContext('bgm.tracks[0].url',ctx),'/audio/ten-coins-left.mp3');vm.runInContext('enterGameLand()',ctx);assert.equal(plays,1);assert.equal(vm.runInContext('bgm.audio.src',ctx),'/audio/ten-coins-left.mp3');assert(splashDismissed&&splashRemoved);vm.runInContext('bgmPlay(3)',ctx);assert.equal(plays,1);vm.runInContext("saveData.ownedBgm.push('bgm_coffee');bgmPlay(3)",ctx);assert.equal(plays,2);ctx.document.hidden=true;listeners.visibilitychange();assert(vm.runInContext('bgm.audio.paused',ctx));ctx.document.hidden=false;listeners.visibilitychange();assert.equal(plays,3);vm.runInContext('bgmStop()',ctx);assert.equal(vm.runInContext('bgm.tracks.length',ctx),12);ctx.document.hidden=true;listeners.visibilitychange();ctx.document.hidden=false;listeners.visibilitychange();assert.equal(plays,3);vm.runInContext('bgmSetVol(0)',ctx);assert.equal(vm.runInContext('bgm.audio.volume',ctx),0);const before=vm.runInContext('saveData.ownedBgm.length',ctx),medals=vm.runInContext('saveData.gachaMedals',ctx);vm.runInContext("grantBgmGachaItem(BGM_GACHA_ITEMS[0]);grantBgmGachaItem(BGM_GACHA_ITEMS[0])",ctx);assert.equal(vm.runInContext('saveData.ownedBgm.length',ctx),before);assert.equal(vm.runInContext('saveData.gachaMedals',ctx),medals);console.log('PASS: splash, locked/unlocked BGM, duplicate without compensation, playback, pause/resume, stop, mute');})();
