const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('dist/client/index.html','utf8');
const start=html.indexOf("const DIRECT_POINT_GAMES");
const end=html.indexOf("function addScore",start);
const ctx={saveData:{scoreHistory:[]},Math,Number};
vm.createContext(ctx);vm.runInContext(html.slice(start,end),ctx);
const reward=(score,won,game)=>vm.runInContext(`gamePointReward(${score},${won},'${game}')`,ctx);
assert(reward(150,true,'quiz')>reward(150,true,'reaction'),'long quiz is rewarded above quick reaction');
assert(reward(1500,true,'solitaire')>reward(1500,true,'tetris'),'long solitaire gets a duration adjustment');
assert(reward(100000,true,'reaction')<=70,'quick-game reward is capped');
assert(reward(100000,false,'runner')<=25,'loss farming is capped');
const normal=reward(500,true,'memory');
ctx.saveData.scoreHistory=[{gameId:'quiz'}];const variety=reward(500,true,'memory');
ctx.saveData.scoreHistory=[{gameId:'memory'},{gameId:'memory'}];const repeated=reward(500,true,'memory');
assert(variety>normal&&repeated<normal,'variety bonus and repeat reduction apply');
assert.match(html,/3種類のゲームをプレイ/);
assert.match(html,/ゲーム報酬を合計150pt獲得/);
assert.match(html,/count===10\?4500:500/);
assert.match(html,/const cost=count\*500/);
console.log('PASS: per-game reward tuning, variety incentive, loss cap, missions and 500pt gacha economy');
